name: PpVanish
version: ${project.version}
main: com.pepe.ppvanish.PpVanish
api-version: 1.16
authors: [ EuropeanPepe ]
description: Vanish aka Disapear
website: pepecraft.com
commands:
  ppvanish:
    description: vanish
    aliases: []
permissions:
  ppvanish.vanish
